site_name: auth-rsha
site_description: Reusable JWT auth for FastAPI (password flow)
site_url: https://sargsyanhayko.github.io/rsha_auth/
repo_url: https://github.com/sargsyanhayko/rsha_auth
repo_name: sargsyanhayko/rsha_auth

docs_dir: src/auth_rsha/docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

nav:
  - Overview: index.md
  - Getting started: getting-started.md
  - API: api.md
  - Changelog: changelog.md

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
